### ISSUE TITLE
Tabbar widget event

### ISSUE THREAD

**Issue by thanhnguyen1121** [sourcemain/tab_container#1]
hi, I faced problem. I can not to catch the event of the widget located inside the tab.

**Comment by sourcemain** [comment]
Thanks for letting me know. Can you please provide a code example of the issue?

**Comment by AndroidDev68** [comment]
I solved this problem by using the callback to trigger the OffSet of the click event. Then on TabContainer callback I check if widget contains that Offset

Here is my code: 
Inside RenderTabFrame: 
<img width="617" alt="Screen Shot 2022-04-22 at 22 09 55" src="https://user-images.githubusercontent.com/84059759/164742743-bb068f15-5bea-4a4a-96f8-71db036947d2.png">

We need caculate some variable:

<img width="656" alt="Screen Shot 2022-04-22 at 22 16 09" src="https://user-images.githubusercontent.com/84059759/164744025-7b935103-479b-42b8-ac3c-291d75a7f77d.png">

When use TabContainer:
<img width="647" alt="Screen Shot 2022-04-22 at 22 13 55" src="https://user-images.githubusercontent.com/84059759/164743460-655fd5c3-7d47-477e-b3a4-a0968822659e.png">

And function check click inside widget:
<img width="647" alt="Screen Shot 2022-04-22 at 22 14 36" src="https://user-images.githubusercontent.com/84059759/164743596-995e7461-8a2f-4a2b-a243-c7064677d767.png">

**Comment by rajesh-h** [comment]
@AndroidDev68  Apologies for tagging you here. I am in need of assistance, will you be able to assist me? I want to know currentActive tab so I can change textColor of my tabs, this is not StringTab.

https://github.com/sourcemain/tab_container/issues/4

**Comment by sourcemain** [comment]
Fixed in version 3
