### ISSUE TITLE
isScrollable attribute

### ISSUE THREAD

**Issue by NaarGes** [sourcemain/tab_container#12]
Hi, 
There is no option to have the TabContainer scrollable instead of make them small and fit them on device width.

**Comment by lbottona** [comment]
Hi, I would like this feature too, but I can see you had no answer back. @NaarGes how did you solve this problem?

**Comment by NaarGes** [comment]
@lbottona I just give up using this repository

**Comment by lbottona** [comment]
@NaarGes I would try to implement it by myself. if you want collaborate I can invite you to the repo.

**Comment by sourcemain** [comment]
Added in version 3.1
