### ISSUE TITLE
Issue with IconButton Not Registering Click Events Inside Tab Container

### ISSUE THREAD

**Issue by muziyuqi** [sourcemain/tab_container#17]
Hello,

I've encountered an issue while using the tab_container feature. I've added an IconButton inside a tab, but it seems that the IconButton is not recognizing click events. I'm wondering if this is due to the tab possibly intercepting or blocking the click events intended for the IconButton.

Here's a brief description of my setup:

I'm using the tab_container widget.
Inside one of the tabs, I've placed an IconButton.
When clicking on the IconButton, no click events are being detected or triggered.
Could you please help me understand if this is a known issue, or if there's a specific way to handle click events for elements inside a tab? Any guidance or workaround to resolve this issue would be greatly appreciated.

Thank you for your time and assistance.

**Comment by sourcemain** [comment]
Fixed in version 3
