### ISSUE TITLE
Slidable tab

### ISSUE THREAD

**Issue by Huzhengtao** [sourcemain/tab_container#3]
excellent! But I have many tabs, and I need a slidable tab bar. Can this be achieved?

**Comment by Mohamed-Essam97** [comment]
+1

**Comment by Mohamed-Essam97** [comment]
+1

**Comment by hkpanchani** [comment]
+1

**Comment by giantss** [comment]
+1

**Comment by lbottona** [comment]
@Huzhengtao I have the same request but I can see no-one have solved this. Have you found some solutions?

**Comment by sourcemain** [comment]
Added in 3.1
